// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4qxmM03-d7lRKN9H37XVg4Zk-hhCYDsY',
    appId: '1:130130343340:web:8a1b22ff434b19f447f609',
    messagingSenderId: '130130343340',
    projectId: 'democracy-simulator',
    authDomain: 'democracy-simulator.firebaseapp.com',
    storageBucket: 'democracy-simulator.appspot.com',
    measurementId: 'G-W4X6WMHWM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuqecTbL5bRNOjQgOZpWW0luPo_ICmAkc',
    appId: '1:130130343340:android:3ecbc8540a7586a447f609',
    messagingSenderId: '130130343340',
    projectId: 'democracy-simulator',
    storageBucket: 'democracy-simulator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSAkgoyyiUtGqc2xoZQ6-HawS4Fxoo5g',
    appId: '1:130130343340:ios:3337666e6d90b03547f609',
    messagingSenderId: '130130343340',
    projectId: 'democracy-simulator',
    storageBucket: 'democracy-simulator.appspot.com',
    iosBundleId: 'co.cococode.democracysimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqSAkgoyyiUtGqc2xoZQ6-HawS4Fxoo5g',
    appId: '1:130130343340:ios:d5830fbdf467bd7d47f609',
    messagingSenderId: '130130343340',
    projectId: 'democracy-simulator',
    storageBucket: 'democracy-simulator.appspot.com',
    iosBundleId: 'com.example.sustainaville.RunnerTests',
  );
}
